### ISSUE TITLE
create_spatial_index throws "No index provider 'spatial' found" for Neo4j 3.0

### ISSUE THREAD

**Issue by seenickcode** [maxdemarzi/neography#212]
Hello.

Does Neography Support Neo4j 3.0 with the Neo4j Spatial Plugin still?

It seems that ``$neo.create_spatial_index("myindex")`` throws the following error with Neo4j 3.0 and Neo4j-Spatial.  On the other hand, it works fine with Neo4j 2.3.1.

````
Neography::NeographyError: NeographyError: 
--message: No index provider 'spatial' found. Maybe the intended provider (or one more of its dependencies) aren't on the classpath or it failed to load., 
--code: 400, 
--stacktrace: , 
--request: {:path=>"/db/data/index/node", :body=>"{\"name\":\"venues\",\"config\":{\"provider\":\"spatial\",\"geometry_type\":\"point\",\"lat\":\"lat\",\"lon\":\"lon\"}}"}, 
--index: 0
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/connection.rb:250:in `raise_errors'
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/connection.rb:222:in `handle_4xx_500_response'
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/connection.rb:193:in `return_result'
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/connection.rb:164:in `evaluate_response'
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/connection.rb:76:in `block (3 levels) in <class:Connection>'
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/connection.rb:89:in `log'
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/connection.rb:67:in `block (2 levels) in <class:Connection>'
	from /Users/seenickcode/.rvm/gems/ruby-2.1.2/gems/neography-1.8.0/lib/neography/rest/spatial.rb:120:in `create_spatial_index'
	from (irb):85
	from /Users/seenickcode/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
````

I'm using Neography 1.8.0, Neo4j 3.0 and the Neo4j Spatial Plugin (downloaded via ``https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.19-neo4j-3.0.3/neo4j-spatial-0.19-neo4j-3.0.3-server-plugin.jar?raw=true``)

I have confirmed that the plugin is installed for Neo4j 3.0 via:
````
curl -u neo4j:neo4j -H "Content-Type: application/json" -X POST -d '{"query":"CALL spatial.procedures"}' http://localhost:7474/db/data/cypher
{
  "columns" : [ "name", "signature" ],
  "data" : [ [ "spatial.addPointLayerWithConfig", "spatial.addPointLayerWithConfig(name :: STRING?, encoderConfig :: STRING?) :: (node :: NODE?)" ], [ "spatial.addNode", "spatial.addNode(layerName :: STRING?, node :: NODE?) :: (node :: NODE?)" ], [ "spatial.importShapefileToLayer", "spatial.importShapefileToLayer(layerName :: STRING?, uri :: STRING?) :: (node :: NODE?)" ], [ "spatial.decodeGeometry", "spatial.decodeGeometry(layerName :: STRING?, coordinate :: NODE?) :: (geometry :: ANY?)" ], [ "spatial.addPointLayerXY", "spatial.addPointLayerXY(name :: STRING?, xProperty :: STRING?, yProperty :: STRING?) :: (node :: NODE?)" ], [ "spatial.addPointLayer", "spatial.addPointLayer(name :: STRING?) :: (node :: NODE?)" ], [ "spatial.addWKT", "spatial.addWKT(layerName :: STRING?, geometry :: STRING?) :: (node :: NODE?)" ], [ "spatial.asExternalGeometry", "spatial.asExternalGeometry(geometry :: ANY?) :: (geometry :: ANY?)" ], [ "spatial.removeLayer", "spatial.removeLayer(name :: STRING?) :: VOID" ], [ "spatial.bbox", "spatial.bbox(layerName :: STRING?, min :: ANY?, max :: ANY?) :: (node :: NODE?)" ], [ "spatial.addLayer", "spatial.addLayer(name :: STRING?, type :: STRING?, encoderConfig :: STRING?) :: (node :: NODE?)" ], [ "spatial.importShapefile", "spatial.importShapefile(uri :: STRING?) :: (node :: NODE?)" ], [ "spatial.addLayerWithEncoder", "spatial.addLayerWithEncoder(name :: STRING?, encoder :: STRING?, encoderConfig :: STRING?) :: (node :: NODE?)" ], [ "spatial.addNodes", "spatial.addNodes(layerName :: STRING?, nodes :: LIST? OF NODE?) :: (node :: NODE?)" ], [ "spatial.addWKTs", "spatial.addWKTs(layerName :: STRING?, geometry :: LIST? OF STRING?) :: (node :: NODE?)" ], [ "spatial.layer", "spatial.layer(name :: STRING?) :: (node :: NODE?)" ], [ "spatial.intersects", "spatial.intersects(layerName :: STRING?, geometry :: ANY?) :: (node :: NODE?)" ], [ "spatial.updateFromWKT", "spatial.updateFromWKT(layerName :: STRING?, geometry :: STRING?, geometryNodeId :: INTEGER?) :: (node :: NODE?)" ], [ "spatial.layers", "spatial.layers() :: (name :: STRING?, signature :: STRING?)" ], [ "spatial.layerTypes", "spatial.layerTypes() :: (name :: STRING?, signature :: STRING?)" ], [ "spatial.asGeometry", "spatial.asGeometry(geometry :: ANY?) :: (geometry :: ANY?)" ], [ "spatial.procedures", "spatial.procedures() :: (name :: STRING?, signature :: STRING?)" ], [ "spatial.withinDistance", "spatial.withinDistance(layerName :: STRING?, coordinate :: ANY?, distanceInKm :: FLOAT?) :: (node :: NODE?, distance :: FLOAT?)" ], [ "spatial.addWKTLayer", "spatial.addWKTLayer(name :: STRING?, nodePropertyName :: STRING?) :: (node :: NODE?)" ], [ "spatial.closest", "spatial.closest(layerName :: STRING?, coordinate :: ANY?, distanceInKm :: FLOAT?) :: (node :: NODE?)" ] ]
````

**Comment by pmackay** [comment]
I am also seeing this using `neo4jrb_spatial` gem (which is heavily based on neography implementation, so perhaps the cause is the same).
